#!/usr/bin/env python

from __future__ import print_function
import os.path
import sys
import subprocess

PKG_MGRS = [
    '/usr/bin/apt',
    '/usr/local/bin/brew'
]

def main():
    pkg_mgr = get_pkg_mgr()
    subprocess.call([pkg_mgr] + sys.argv[1:])

def get_pkg_mgr():
    mgrs = [p for p in PKG_MGRS if os.path.isfile(p)]
    if mgrs:
        return mgrs[0]
    else:
        print('No supported package manager found. Expected one of', 
              ', '.join(PKG_MGRS))
        sys.exit(1)

if __name__ == '__main__': 
    main()

